package com.entrepidea.algo.leetcode.easy;

import org.junit.Assert;
import org.junit.Test;
/**
 * @Desc:
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 *
 * @Source: https://leetcode.com/problems/find-the-difference/
 *
 * @Date: 04/18/20
 *
 * */
public class LE389FindDiff {
    private char findDiff(String s, String t){
        int[] benchMark = new int[26];
        char[] tChars = t.toCharArray();
        for(char c : tChars){
            int index = c - 'a';
            benchMark[index]++;
        }
        char[] sChars = s.toCharArray();
        for(char c : sChars){
            int index = c - 'a';
            benchMark[index]--;
        }
        char ch = 'a';
        for(int idx = 0;idx<benchMark.length;idx++){
            if(benchMark[idx]!=0){
                ch += idx;
                break;
            }
        }
        return ch;
    }

    @Test
    public void test(){
        String s1 = "abcd";
        String t1 = "cabde";
        Assert.assertTrue(findDiff(s1,t1)=='e');

        String s2 = "qwerty";
        String t2 = "yertwqz";
        Assert.assertTrue(findDiff(s2,t2)=='z');
    }
}
