"""
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
https://leetcode.com/problems/find-the-difference/

Date: 10/29/21

"""
def diff(s,t) ->chr:
    al = [0]*26
    l = list(s)
    for e in l:
        al[ord(e)-ord('a')] += 1
    
    l = list(t)
    for e in l:
        if al[ord(e)-ord('a')] == 0:
            return e
        else:
            al[ord(e)-ord('a')] -= 1
    

if __name__ == '__main__':
    s = 'abcd'
    t = 'abcde'
    print(diff(s,t))
    s = 'a'
    t = 'aa'
    print(diff(s,t))
    s = 'ae'
    t = 'aea'
    print(diff(s,t))
    
