"""
THIS IS MY FIRST PROJECT.DON'T DELETE IT.
DATE: 10/17/21
"""
#TOUCH THE RIGHT HERE WITH THE ARROW KEYS,THEN CLICK THE BIG KEY WITH NOTHING ON IT.THEN CLICK THE <- KEY AND TYPE YOUR NAME.
name = 'Aaron'                       
print('hello, ' + name)
